//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEST_SHARP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lop
    {
        public string id_lop { get; set; }
        public string id_sv { get; set; }
        public string ten_lop { get; set; }
    
        public virtual Lop Lop1 { get; set; }
        public virtual Lop Lop2 { get; set; }
    }
}
