//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEST_SHARP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SinhVien
    {
        public string id_sv { get; set; }
        public string hoten_sv { get; set; }
        public string diachi_sv { get; set; }
        public Nullable<bool> gioitinh_sv { get; set; }
        public string sdt_sv { get; set; }
    }
}
